name: UUP linux workflow

on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
      version:
        required: true
      release:
        required: true
jobs:
  make_iso:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare Build Environment
      run: |
           sudo apt update -y && sudo apt install -y cabextract curl wimtools chntpw genisoimage php
           cd $HOME
           git clone https://github.com/linuxop/windows-images-ci

    - name: Make ISO
      run: |
           cd $HOME/windows-images-ci/${{ github.event.inputs.arch }}/${{ github.event.inputs.version }}/${{ github.event.inputs.release }}
           bash uup_download_linux.sh

    - name: Upload ISO
      run: |
           cd $HOME/windows-images-ci/${{ github.event.inputs.arch }}/${{ github.event.inputs.version }}/${{ github.event.inputs.release }}
           sudo chmod 0777 *.iso
           export iso=$(echo *.iso)
           curl -F "file=@$iso" https://api.bayfiles.com/upload




