name: UUP linux workflow

on:
  workflow_dispatch:
    inputs:
      configlink:
        required: true
jobs:
  make_iso:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare Build Environment
      run: |
           sudo apt update -y && sudo apt install sudo apt install -y cabextract wimtools chntpw genisoimage 
           cd $HOME
           git clone https://github.com/linuxop/windows-images-ci
