name: UUP linux workflow

on:
  workflow_dispatch:
    inputs:
      configlink:
        required: true
jobs:
  make_iso:
    runs-on: ubuntu:latest

    steps:
    - name: Download config
      run: wget ${{ github.event.inputs.configlink }}
