name: UUP windows workflow

on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
      version:
        required: true
      release:
        required: true
jobs:
  make_iso:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
    - name: Prepare Build Environment
      run: |
           C:
           git clone https://github.com/elytr/windows-uup-images
           choco install curl

    - name: Make ISO
      run: |
            C:
            Set-Location .\windows-uup-images\${{ github.event.inputs.arch }}\${{ github.event.inputs.version }}\${{ github.event.inputs.release }}
            .\uup_download_windows.cmd

    - name: Upload ISO
      run: |
           C:
           Set-Location .\windows-uup-images\${{ github.event.inputs.arch }}\${{ github.event.inputs.version }}\${{ github.event.inputs.release }}
           curl.exe --upload-file "file=@*.ISO" https://api.bayfiles.com/upload



